disableStartupPopups: true

gui:

  theme:
    defaultFgColor:
      - "#c8c8c8"
    activeBorderColor:
      - "#c8c8c8"
      - bold
    inactiveBorderColor:
      - "#888888"
    searchingActiveBorderColor:
      - "#deb39c"
      - bold
    optionsTextColor:
      - "#525252"
    selectedLineBgColor:
      - "#383838"
    inactiveViewSelectedLineBgColor:
      - "#383838"
    # cherryPickedCommitBgColor:
    #   - "#45475a"
    # cherryPickedCommitFgColor:
    #   - "#89b4fa"
    # unstagedChangesColor:
    #   - red

  authorColors:
    "*": "#888888"

  scrollHeight: 3
  nerdFontsVersion: "3"
  showFileIcons: false
  showBottomLine: false
  # showRootItemInFileTree: false

  # keybindings:
  #   universal:
  #     quit: <esc>
