[mgr]
cwd = { fg = "#8b8b8b" }
border_style = { fg = "#363636" }
find_keyword = { fg = "green", bg = "#363636", bold = true }
find_position = { fg = "#202020", bg = "blue", bold = true }
syntect_theme = "~/.config/yazi/onyx.tmTheme"

[indicator]
parent = { bg = "#363636", bold = true }
current = { fg = "#202020", bg = "blue", bold = true }
preview = { bg = "#363636", bold = true }
padding = { open = "█", close = "█" }

[tabs]
active = { bg = "blue", fg = "#202020", bold = true }
inactive = { bg = "#363636", fg = "#c8c8c8" }

[mode]
normal_main = { fg = "#202020", bg = "blue", bold = true }
normal_alt = { fg = "#c8c8c8", bg = "#363636", bold = false }
select_main = { fg = "#202020", bg = "green", bold = true }
select_alt = { fg = "#c8c8c8", bg = "#363636", bold = false }
unset_main = { fg = "#202020", bg = "magenta", bold = true }
unset_alt = { fg = "#c8c8c8", bg = "#363636", bold = false }

[confirm]
border = { fg = "#8b8b8b", bold = true }
title = { fg = "#c8c8c8", bold = true }
btn_yes = { bg = "blue", fg = "#202020", bold = true }

[spot]
border = { fg = "#8b8b8b", bold = true }
title = { fg = "#c8c8c8", bold = true }
tbl_cell = { bg = "blue", fg = "#202020", bold = true }
tbl_col = { fg = "#c8c8c8" }

[input]
border = { fg = "#c8c8c8", bold = true }
title = { fg = "#c8c8c8", bold = true }

[filetype]
rules = [
    { mime = "inode/empty", fg = "#525252" },
    { url = "*", is = "orphan", fg = "red" },
    { url = "*", fg = "#8b8b8b" },
    { url = "*/", fg = "#c8c8c8" }
]
