backend = "auto"
smoothing = true
startup_duration = 1

night_temp = 3500
day_temp = 6500
night_gamma = 100
day_gamma = 100

transition_mode = "center"
sunset = "22:00:00"
sunrise = "10:00:00"
transition_duration = 120
update_interval = 60
